version: "3"
services:
  task.database:
    env_file: "./_docker-compose-env/task-database.env"
    ports:
      - "27017:27017"
    build:
      dockerfile: dockerfile
      context: task-database
  identity.database:
    env_file: "./_docker-compose-env/identity-database.env"
    ports:
      - "3306:3306"
    build:
      dockerfile: dockerfile
      context: identity-database
  task.service:
    depends_on:
      - identity.database
      - task.database
    build:
      dockerfile: dockerfile
      context: task-service
    ports:
      - "3000:3000"
    volumes:
      - /root/app/node_modules
      - ./task-service:/root/app
