version: "3"
services:
  mysql:
    env_file: "./_docker-compose-env/database.env"
    ports:
      - "33061:3306"
    build:
      dockerfile: dockerfile
      context: database
  backend:
    env_file:
      - path: "./_docker-compose-env/database.env"
      - path: "./_docker-compose-env/backend.env"
    depends_on:
      - mysql
    build:
      dockerfile: dockerfile
      context: server
    ports:
      - "8000:8000"
    volumes:
      - /root/app/node_modules
      - ./server:/root/app
  frontend:
    depends_on:
      - backend
    build:
      dockerfile: dockerfile
      context: client
    ports:
      - "3000:80"
    volumes:
      - /root/app/node_modules
      - ./client:/root/app
