apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-task
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000