apiVersion: v1
kind: Service
metadata:
  name: identity-database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-id-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
