apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-id
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
