apiVersion: v1
kind: Service
metadata:
  name: task-database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-task-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
